void cadre()
{
move(5,41);
addstr("  /= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = == = = = = = = = \\");
move(6,40);
addstr("  / = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = == = = = = = = = =\\");
move(7,40);
addstr(" ||                                                                               ||");
move(8,40);
addstr(" ||                                                                               ||");
move(9,40);
addstr(" ||                                                                               ||");
move(10,40);
addstr(" ||                                                                               ||");
move(11,40);
addstr(" ||                                                                               ||"); 
move(12,40);
addstr(" ||                                                                               ||");
move(13,40);
addstr(" ||                                                                               ||");
move(14,40);
addstr(" ||                                                                               ||"); 
move(15,40);
addstr(" ||                                                                               ||");
move(16,40);
addstr(" ||                                                                               ||");
move(17,40);  
addstr(" ||                                                                               ||");
move(18,40);  
addstr(" ||                                                                               ||");
move(19,40);
addstr(" ||                                                                               ||");
move(20,40);
addstr(" ||                                                                               ||");
move(21,40);
addstr(" ||                                                                               ||");
move(22,40);
addstr(" ||                                                                               ||");
move(23,40);
addstr(" ||                                                                               ||");
move(24,40);
addstr(" ||                                                                               ||");
move(25,40);
addstr(" ||                                                                               ||");
move(26,40);
addstr(" ||                                                                               ||");
move(27,40);
addstr(" ||                                                                               ||");
move(28,40);
addstr(" ||                                                                               ||");
move(29,40);
addstr(" ||                                                                               ||");
move(30,40);
addstr(" ||                                                                               ||");
move(31,40);
addstr(" ||                                                                               ||");
move(32,40);
addstr(" ||                                                                               ||");
move(33,40);
addstr(" \\= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = == = = = = = = =/");
move(34,41);
addstr("  \\= = = = = = = = = = = = = = = = = = = = = = = == = = = = = = = = = = = = = = =/");

}
